### ISSUE TITLE
Updating/work-with this template for Azd Devcontainer feature.

### ISSUE THREAD

**Issue by zedy-wj** [savannahostrowski/python-mercury-notebooks-azd#9]
We are updating this template to support new features in `Azd Devcontainer`.

For the Azd Devcontainer feature: We will add  the following code in `devcontainer.json` file.

``` 
"ghcr.io/azure/azure-dev/azd:latest": {}
``` 

@rajeshkamal5050 , @savannahostrowski for notification.

**Comment by savannahostrowski** [comment]
Updated
